ALTER TABLE user_team FORCE ROW LEVEL SECURITY;
ALTER TABLE team FORCE ROW LEVEL SECURITY;
ALTER TABLE repo FORCE ROW LEVEL SECURITY;
ALTER TABLE pipeline FORCE ROW LEVEL SECURITY;
ALTER TABLE pipeline_job FORCE ROW LEVEL SECURITY;
ALTER TABLE pipeline_job_step FORCE ROW LEVEL SECURITY;
