// This file has been generated by Specta. Do not edit this file manually.
export type EventMessage = { t: "updatePipelineStatus"; p: {
	pipeline: string,
	status: PipelineStatusResponse,
} } | { t: "updateJobStatus"; p: {
	pipeline: string,
	job: string,
	status: JobStatusResponse,
} };

export type JobStatusResponse = "waiting" | "pending" | "running" | "success" | "failed" | "skipped" | "cancelled";

export type PipelineStatusResponse = "queued" | "running" | "success" | "failed" | "cancelled";
